spring:
  application:
    name: shardingdemo
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-config.yaml



mybatis:
  mapper-locations: classpath:/mapping/**.xml