server:
  port: 9002
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql:///security-demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: goudan125
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: localhost:8848
      #      server-addr: nacos.etongeis.com:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
dubbo:
  scan:
    base-packages: com.example
  registry:
    address: nacos://${spring.cloud.nacos.server-addr}?username=${spring.cloud.nacos.username}&password=${spring.cloud.nacos.password}&namespace=public
    username: ${spring.cloud.nacos.username}
    password: ${spring.cloud.nacos.password}
    register: true
    subscribe: true
    server: inventory-service
  consumer:
    check: false
    retries: 0
  protocol:
    name: dubbo
    port: -1