my:
  server:
    port: 8003
server:
  servlet:
    session:
      cookie:
        name: c3


security:
  oauth2:
    client:
      client-secret: test123
      client-id: test
      user-authorization-uri: http://localhost:8000/oauth/authorize
      access-token-uri: http://localhost:8000/oauth/token
    resource:
      user-info-uri: http://localhost:8000/user/info