spring:
  datasource:
    url: jdbc:mysql://${run.mysql.url:goudan.online:3306}/video-download?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: goudan125
  mvc:
    view:
      prefix: /page/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/static

server:
  port: 80

mybatis:
  mapper-locations: classpath:/mapping/*.xml

