spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: true
      routes:
        - id: demo-service
          uri: lb://demo-service
          predicates:
            - Path=/api/demo/**
          filters:
            - StripPrefix=1
      metrics:
        enabled: true
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
        register-enabled: true
        username: nacos
        password: nacos

server:
  port: 80

